# Generated by Django 6.1 on 2026-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Haircut', 'Haircut'), ('Beard', 'Beard'), ('Hair Color', 'Hair Color'), ('Facial', 'Facial'), ('Hair Styling', 'Hair Styling'), ('Hair Spa', 'Hair Spa'), ('Other', 'Other')], default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='quality',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], default='Basic', max_length=50),
        ),
    ]
